### ISSUE TITLE
TODO for v1 release

### ISSUE THREAD

**Issue by horiuchi** [horiuchi/dtsgenerator#276]
- [v] support JSON Schema Draft 07 and OpenAPI v3
- [ ] remove unused command line options
- [ ] add the document of usage as a library for changing Type name rule.
- [ ] add the document of supporting element of each spec
